const MOVEMENTS = {
  ROCK: 'ROCK',
  PAPER: 'PAPER',
  SCISSORS: 'SCISSORS',
};

const MOVEMENT_SCORE = {
  [MOVEMENTS.ROCK]: 1,
  [MOVEMENTS.PAPER]: 2,
  [MOVEMENTS.SCISSORS]: 3,
};

const ROUND_RESULTS = {
  LOST: 'LOST',
  DRAW: 'DRAW',
  WON: 'WON',
};

const ROUND_SCORES = {
  [ROUND_RESULTS.LOST]: 0,
  [ROUND_RESULTS.DRAW]: 3,
  [ROUND_RESULTS.WON]: 6,
};

const OPPONENT_MOVEMENTS = {
  A: MOVEMENTS.ROCK,
  B: MOVEMENTS.PAPER,
  C: MOVEMENTS.SCISSORS,
};

const ME_MOVEMENTS = {
  X: MOVEMENTS.ROCK,
  Y: MOVEMENTS.PAPER,
  Z: MOVEMENTS.SCISSORS,
};

const VS_MOVEMENTS_RESULT = {
  [`${MOVEMENTS.ROCK}${MOVEMENTS.ROCK}`]: ROUND_RESULTS.DRAW,
  [`${MOVEMENTS.ROCK}${MOVEMENTS.PAPER}`]: ROUND_RESULTS.LOST,
  [`${MOVEMENTS.ROCK}${MOVEMENTS.SCISSORS}`]: ROUND_RESULTS.WON,

  [`${MOVEMENTS.PAPER}${MOVEMENTS.ROCK}`]: ROUND_RESULTS.WON,
  [`${MOVEMENTS.PAPER}${MOVEMENTS.PAPER}`]: ROUND_RESULTS.DRAW,
  [`${MOVEMENTS.PAPER}${MOVEMENTS.SCISSORS}`]: ROUND_RESULTS.LOST,

  [`${MOVEMENTS.SCISSORS}${MOVEMENTS.ROCK}`]: ROUND_RESULTS.LOST,
  [`${MOVEMENTS.SCISSORS}${MOVEMENTS.PAPER}`]: ROUND_RESULTS.WON,
  [`${MOVEMENTS.SCISSORS}${MOVEMENTS.SCISSORS}`]: ROUND_RESULTS.DRAW,
};

const ROUND_DESIRED_RESULT = {
  X: ROUND_RESULTS.LOST,
  Y: ROUND_RESULTS.DRAW,
  Z: ROUND_RESULTS.WON,
};

const MOVEMENT_RESPONSE = {
  [ROUND_RESULTS.WON]: {
    [MOVEMENTS.ROCK]: MOVEMENTS.PAPER,
    [MOVEMENTS.PAPER]: MOVEMENTS.SCISSORS,
    [MOVEMENTS.SCISSORS]: MOVEMENTS.ROCK,
  },

  [ROUND_RESULTS.DRAW]: {
    [MOVEMENTS.ROCK]: MOVEMENTS.ROCK,
    [MOVEMENTS.PAPER]: MOVEMENTS.PAPER,
    [MOVEMENTS.SCISSORS]: MOVEMENTS.SCISSORS,
  },

  [ROUND_RESULTS.LOST]: {
    [MOVEMENTS.ROCK]: MOVEMENTS.SCISSORS,
    [MOVEMENTS.PAPER]: MOVEMENTS.ROCK,
    [MOVEMENTS.SCISSORS]: MOVEMENTS.PAPER,
  },
};

module.exports = {
  ME_MOVEMENTS,
  MOVEMENTS,
  MOVEMENT_SCORE,
  OPPONENT_MOVEMENTS,
  ROUND_RESULTS,
  ROUND_SCORES,
  VS_MOVEMENTS_RESULT,
  ROUND_DESIRED_RESULT,
  MOVEMENT_RESPONSE,
};
